# Задание 1. Загрузка данных
Изучить представленный набор данных на основе описания его столбцов, загрузить его и оставить 8 столбцов для дальнейшего изучения: surgery?, Age, rectal temperature, pulse, respiratory rate, temperature of extremities, pain, outcome.

# Задание 2. Первичное изучение данных
Проанализировать значения по столбцам, рассчитать базовые статистики, найти выбросы.

# Задание 3. Работа с пропусками
Рассчитать количество пропусков для всех выбранных столбцов. Принять и обосновать решение о методе заполнения пропусков по каждому столбцу на основе рассчитанных статистик и возможной взаимосвязи значений в них. Сформировать датафрейм, в котором пропуски будут отсутствовать.

In [1]:
import pandas as pd
import numpy as np

In [91]:
hd = pd.read_csv('horse_data.csv',na_values='?')
hd.head

<bound method NDFrame.head of        2  1   530101  38.50     66    28    3  3.1    ?  2.1  ...  45.00  \
0    1.0  1   534817   39.2   88.0  20.0  NaN  NaN  4.0  1.0  ...   50.0
1    2.0  1   530334   38.3   40.0  24.0  1.0  1.0  3.0  1.0  ...   33.0
2    1.0  9  5290409   39.1  164.0  84.0  4.0  1.0  6.0  2.0  ...   48.0
3    2.0  1   530255   37.3  104.0  35.0  NaN  NaN  6.0  2.0  ...   74.0
4    2.0  1   528355    NaN    NaN   NaN  2.0  1.0  3.0  1.0  ...    NaN
..   ... ..      ...    ...    ...   ...  ...  ...  ...  ...  ...    ...
294  1.0  1   533886    NaN  120.0  70.0  4.0  NaN  4.0  2.0  ...   55.0
295  2.0  1   527702   37.2   72.0  24.0  3.0  2.0  4.0  2.0  ...   44.0
296  1.0  1   529386   37.5   72.0  30.0  4.0  3.0  4.0  1.0  ...   60.0
297  1.0  1   530612   36.5  100.0  24.0  3.0  3.0  3.0  1.0  ...   50.0
298  1.0  1   534618   37.2   40.0  20.0  NaN  NaN  NaN  NaN  ...   36.0

     8.40  ?.4  ?.5  2.2  2.3  11300  00000  00000.1  2.4
0    85.0  2.0  2.0  3.0    2   2208      0        0    2
1     6.7  NaN  NaN  1.0    2      0      0        0    1
2     7.2  3.0  5.3  2.0    1   2208      0        0    1
3     7.4  NaN  NaN  2.0    2   4300      0        0    2
4     NaN  NaN  NaN  1.0    2      0      0        0    2
..    ...  ...  ...  ...  ...    ...    ...      ...  ...
294  65.0  NaN  NaN  3.0    2   3205      0        0    2
295   NaN  3.0  3.3  3.0    1   2208      0        0    1
296   6.8  NaN  NaN  2.0    1   3205      0        0    2
297   6.0  3.0  3.4  1.0    1   2208      0        0    1
298  62.0  1.0  1.0  3.0    2   6112      0        0    2

[299 rows x 28 columns]>

In [13]:
f = open('horse_data.names', 'r')
for line in f:
    print (line)

1. TItle: Horse Colic database



2. Source Information

   -- Creators: Mary McLeish & Matt Cecile

	  	Department of Computer Science

		University of Guelph

		Guelph, Ontario, Canada N1G 2W1

		mdmcleish@water.waterloo.edu

   -- Donor:    Will Taylor (taylor@pluto.arc.nasa.gov)

   -- Date:     8/6/89



3. Past Usage:

   -- Unknown



4. Relevant Information:



   -- 2 data files

      -- horse-colic.data: 300 training instances

      -- horse-colic.test: 68 test instances

   -- Possible class attributes: 24 (whether lesion is surgical)

     -- others include: 23, 25, 26, and 27

   -- Many Data types: (continuous, discrete, and nominal)



5. Number of Instances: 368 (300 for training, 68 for testing)



6. Number of attributes: 28



7. Attribute Information:



  1:  surgery?

          1 = Yes, it had surgery

          2 = It was treated without surgery



  2:  Age

          1 = Adult horse

          2 = Young (< 6 months)



  3:  Hospital Number

          - numeric id

          - the case number assigned to the horse

            (may not be unique if the horse is treated > 1 time)



  4:  rectal temperature

          - linear

          - in degrees celsius.

          - An elevated temp may occur due to infection.

          - temperature may be reduced when the animal is in late shock

          - normal temp is 37.8

          - this parameter will usually change as the problem progresses

               eg. may start out normal, then become elevated because of

                   the lesion, passing back through the normal range as the

                   horse goes into shock

  5:  pulse

          - linear

          - the heart rate in beats per minute

          - is a reflection of the heart condition: 30 -40 is normal for adults

          - rare to have a lower than normal rate although athletic horses

            may have a rate of 20-25

          - animals with painful lesions or suffering from circulatory shock

            may have an elevated heart rate



  6:  respiratory rate

          - linear

          - normal rate is 8 to 10

          - usefulness is doubtful due to the great fluctuations



  7:  temperature of extremities

          - a subjective indication of peripheral circulation

          - possible values:

               1 = Normal

               2 = Warm

               3 = Cool

               4 = Cold

          - cool to cold extremities indicate possible shock

          - hot extremities should correlate with an elevated rectal temp.



  8:  peripheral pulse

          - subjective

          - possible values are:

               1 = normal

               2 = increased

               3 = reduced

               4 = absent

          - normal or increased p.p. are indicative of adequate circulation

            while reduced or absent indicate poor perfusion



  9:  mucous membranes

          - a subjective measurement of colour

          - possible values are:

               1 = normal pink

               2 = bright pink

               3 = pale pink

               4 = pale cyanotic

               5 = bright red / injected

               6 = dark cyanotic

          - 1 and 2 probably indicate a normal or slightly increased

            circulation

          - 3 may occur in early shock

          - 4 and 6 are indicative of serious circulatory compromise

          - 5 is more indicative of a septicemia



 10: capillary refill time

          - a clinical judgement. The longer the refill, the poorer the

            circulation

          - possible values

               1 = < 3 seconds

               2 = >= 3 seconds



 11: pain - a subjective judgement of the horse's pain level

          - possible values:

               1 = alert, no pain

               2 = depressed

               3 = intermittent mild pain

               4 = intermittent severe pain

               5 = continuous severe pain

          - should NOT be treated as a ordered or discrete variable!

          - In general, the more painful, the more likely it is to require

            surgery

          - prior treatment of pain may mask the pain level to some extent



 12: peristalsis

          - an indication of the activity in the horse's gut. As the gut

            becomes more distended or the horse becomes more toxic, the

            activity decreases

          - possible values:

               1 = hypermotile

               2 = normal

               3 = hypomotile

               4 = absent



 13: abdominal distension

          - An IMPORTANT parameter.

          - possible values

               1 = none

               2 = slight

               3 = moderate

               4 = severe

          - an animal with abdominal distension is likely to be painful and

            have reduced gut motility.

          - a horse with severe abdominal distension is likely to require

            surgery just tio relieve the pressure



 14: nasogastric tube

          - this refers to any gas coming out of the tube

          - possible values:

               1 = none

               2 = slight

               3 = significant

          - a large gas cap in the stomach is likely to give the horse

            discomfort



 15: nasogastric reflux

          - possible values

               1 = none

               2 = > 1 liter

               3 = < 1 liter

          - the greater amount of reflux, the more likelihood that there is

            some serious obstruction to the fluid passage from the rest of

            the intestine



 16: nasogastric reflux PH

          - linear

          - scale is from 0 to 14 with 7 being neutral

          - normal values are in the 3 to 4 range



 17: rectal examination - feces

          - possible values

               1 = normal

               2 = increased

               3 = decreased

               4 = absent

          - absent feces probably indicates an obstruction



 18: abdomen

          - possible values

               1 = normal

               2 = other

               3 = firm feces in the large intestine

               4 = distended small intestine

               5 = distended large intestine

          - 3 is probably an obstruction caused by a mechanical impaction

            and is normally treated medically

          - 4 and 5 indicate a surgical lesion



 19: packed cell volume

          - linear

          - the # of red cells by volume in the blood

          - normal range is 30 to 50. The level rises as the circulation

            becomes compromised or as the animal becomes dehydrated.



 20: total protein

          - linear

          - normal values lie in the 6-7.5 (gms/dL) range

          - the higher the value the greater the dehydration



 21: abdominocentesis appearance

          - a needle is put in the horse's abdomen and fluid is obtained from

            the abdominal cavity

          - possible values:

               1 = clear

               2 = cloudy

               3 = serosanguinous

          - normal fluid is clear while cloudy or serosanguinous indicates

            a compromised gut



 22: abdomcentesis total protein

          - linear

          - the higher the level of protein the more likely it is to have a

            compromised gut. Values are in gms/dL



 23: outcome

          - what eventually happened to the horse?

          - possible values:

               1 = lived

               2 = died

               3 = was euthanized



 24: surgical lesion?

          - retrospectively, was the problem (lesion) surgical?

          - all cases are either operated upon or autopsied so that

            this value and the lesion type are always known

          - possible values:

               1 = Yes

               2 = No



 25, 26, 27: type of lesion

          - first number is site of lesion

               1 = gastric

               2 = sm intestine

               3 = lg colon

               4 = lg colon and cecum

               5 = cecum

               6 = transverse colon

               7 = retum/descending colon

               8 = uterus

               9 = bladder

               11 = all intestinal sites

               00 = none

          - second number is type

               1 = simple

               2 = strangulation

               3 = inflammation

               4 = other

          - third number is subtype

               1 = mechanical

               2 = paralytic

               0 = n/a

          - fourth number is specific code

               1 = obturation

               2 = intrinsic

               3 = extrinsic

               4 = adynamic

               5 = volvulus/torsion

               6 = intussuption

               7 = thromboembolic

               8 = hernia

               9 = lipoma/slenic incarceration

               10 = displacement

               0 = n/a

 28: cp_data

          - is pathology data present for this case?

               1 = Yes

               2 = No

          - this variable is of no significance since pathology data

            is not included or collected for these cases



8. Missing values: 30% of the values are missing

In [92]:
hd.columns=['surgery?','age','hospital number', 'rectal temperature', 'pulse', 'respiratory rate', 'temp of extremities', 'periferal pulse', 'mucos mem', 'c r t', 'pain', 'periscalsis', 'ad', 'nt', 'nr', 'nr PH', 're-f', 'abdomen', 'pcv', 't protein', 'aa', 'atp', 'outcome', 's l?', 'sl', 'type', 'stype','cp_data']
hd.head

<bound method NDFrame.head of      surgery?  age  hospital number  rectal temperature  pulse  \
0         1.0    1           534817                39.2   88.0
1         2.0    1           530334                38.3   40.0
2         1.0    9          5290409                39.1  164.0
3         2.0    1           530255                37.3  104.0
4         2.0    1           528355                 NaN    NaN
..        ...  ...              ...                 ...    ...
294       1.0    1           533886                 NaN  120.0
295       2.0    1           527702                37.2   72.0
296       1.0    1           529386                37.5   72.0
297       1.0    1           530612                36.5  100.0
298       1.0    1           534618                37.2   40.0

     respiratory rate  temp of extremities  periferal pulse  mucos mem  c r t  \
0                20.0                  NaN              NaN        4.0    1.0
1                24.0                  1.0              1.0        3.0    1.0
2                84.0                  4.0              1.0        6.0    2.0
3                35.0                  NaN              NaN        6.0    2.0
4                 NaN                  2.0              1.0        3.0    1.0
..                ...                  ...              ...        ...    ...
294              70.0                  4.0              NaN        4.0    2.0
295              24.0                  3.0              2.0        4.0    2.0
296              30.0                  4.0              3.0        4.0    1.0
297              24.0                  3.0              3.0        3.0    1.0
298              20.0                  NaN              NaN        NaN    NaN

     ...   pcv  t protein   aa  atp  outcome  s l?    sl  type  stype  cp_data
0    ...  50.0       85.0  2.0  2.0      3.0     2  2208     0      0        2
1    ...  33.0        6.7  NaN  NaN      1.0     2     0     0      0        1
2    ...  48.0        7.2  3.0  5.3      2.0     1  2208     0      0        1
3    ...  74.0        7.4  NaN  NaN      2.0     2  4300     0      0        2
4    ...   NaN        NaN  NaN  NaN      1.0     2     0     0      0        2
..   ...   ...        ...  ...  ...      ...   ...   ...   ...    ...      ...
294  ...  55.0       65.0  NaN  NaN      3.0     2  3205     0      0        2
295  ...  44.0        NaN  3.0  3.3      3.0     1  2208     0      0        1
296  ...  60.0        6.8  NaN  NaN      2.0     1  3205     0      0        2
297  ...  50.0        6.0  3.0  3.4      1.0     1  2208     0      0        1
298  ...  36.0       62.0  1.0  1.0      3.0     2  6112     0      0        2

[299 rows x 28 columns]>

In [93]:
hd.drop(['hospital number', 'periferal pulse', 'mucos mem', 'c r t', 'periscalsis', 'ad', 'nt', 'nr', 'nr PH', 're-f', 'abdomen', 'pcv', 't protein', 'aa', 'atp', 's l?', 'sl', 'type', 'stype','cp_data'], axis=1, inplace=True)
hd.head

<bound method NDFrame.head of      surgery?  age  rectal temperature  pulse  respiratory rate  \
0         1.0    1                39.2   88.0              20.0
1         2.0    1                38.3   40.0              24.0
2         1.0    9                39.1  164.0              84.0
3         2.0    1                37.3  104.0              35.0
4         2.0    1                 NaN    NaN               NaN
..        ...  ...                 ...    ...               ...
294       1.0    1                 NaN  120.0              70.0
295       2.0    1                37.2   72.0              24.0
296       1.0    1                37.5   72.0              30.0
297       1.0    1                36.5  100.0              24.0
298       1.0    1                37.2   40.0              20.0

     temp of extremities  pain  outcome
0                    NaN   3.0      3.0
1                    1.0   3.0      1.0
2                    4.0   2.0      2.0
3                    NaN   NaN      2.0
4                    2.0   2.0      1.0
..                   ...   ...      ...
294                  4.0   2.0      3.0
295                  3.0   4.0      3.0
296                  4.0   4.0      2.0
297                  3.0   3.0      1.0
298                  NaN   NaN      3.0

[299 rows x 8 columns]>

In [94]:
hd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   surgery?             298 non-null    float64
 1   age                  299 non-null    int64
 2   rectal temperature   239 non-null    float64
 3   pulse                275 non-null    float64
 4   respiratory rate     241 non-null    float64
 5   temp of extremities  243 non-null    float64
 6   pain                 244 non-null    float64
 7   outcome              298 non-null    float64
dtypes: float64(7), int64(1)
memory usage: 18.8 KB

In [106]:
hd.describe()

,surgery?,age,rectal temperature,pulse,respiratory rate,temp of extremities,pain,outcome
count,298.000000,299.00000,239.000000,275.000000,241.000000,243.000000,244.000000,298.000000
mean,1.395973,1.64214,38.166527,71.934545,30.427386,2.345679,2.942623,1.550336
std,0.489881,2.17730,0.733508,28.680522,17.678256,1.046369,1.303993,0.737967
min,1.000000,1.00000,35.400000,30.000000,8.000000,1.000000,1.000000,1.000000
25%,1.000000,1.00000,37.800000,48.000000,18.000000,1.000000,2.000000,1.000000
50%,1.000000,1.00000,38.200000,64.000000,24.000000,3.000000,3.000000,1.000000
75%,2.000000,1.00000,38.500000,88.000000,36.000000,3.000000,4.000000,2.000000
max,2.000000,9.00000,40.800000,184.000000,96.000000,4.000000,5.000000,3.000000

In [95]:
#максимальный возраст лошади
print(hd['age'].max())

9

In [96]:
#минимальный возраст лошади
print(hd['age'].min())

1

In [97]:
(hd.isna().mean() * 100).round(2)

surgery?                0.33
age                     0.00
rectal temperature     20.07
pulse                   8.03
respiratory rate       19.40
temp of extremities    18.73
pain                   18.39
outcome                 0.33
dtype: float64

In [98]:
#основная статистика по возрастам 
print(hd.age.mean())
print(hd.age.median())
print(hd.age.mode()[0])
print(hd.age.std())
print(hd.age.var())

1.6421404682274248
1.0
1
2.1772997793587714
4.740634329195755

In [77]:
lived = hd.loc[hd['outcome'] == '1']
print('выжившие', len(lived),'-', (len(lived)*100/len(hd)), '%')

выжившие 178 - 59.531772575250834 %

In [79]:
died = hd.loc[hd['outcome'] == '2']
print('умершие', len(died),'-', (len(died)*100/len(hd)), '%')

умершие 76 - 25.418060200668897 %

In [80]:
euthanized = hd.loc[hd['outcome'] == '3']
print('усыпленные', len(euthanized),'-', (len(euthanized)*100/len(hd)), '%')

усыпленные 44 - 14.715719063545151 %

In [100]:
hd['pulse'] = hd['pulse'].astype(float)

In [101]:
#выбросы по пульсу
q1 = hd['pulse'].quantile(0.25)
q3 = hd['pulse'].quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - (1.5 * iqr) 
upper_bound = q3 + (1.5 * iqr)
remove_outliers = hd[hd['pulse'].between(lower_bound, upper_bound, inclusive=True)]
remove_outliers

,surgery?,age,rectal temperature,pulse,respiratory rate,temp of extremities,pain,outcome
0,1.0,1,39.2,88.0,20.0,NaN,3.0,3.0
1,2.0,1,38.3,40.0,24.0,1.0,3.0,1.0
3,2.0,1,37.3,104.0,35.0,NaN,NaN,2.0
5,1.0,1,37.9,48.0,16.0,1.0,3.0,1.0
6,1.0,1,NaN,60.0,NaN,3.0,NaN,2.0
...,...,...,...,...,...,...,...,...
294,1.0,1,NaN,120.0,70.0,4.0,2.0,3.0
295,2.0,1,37.2,72.0,24.0,3.0,4.0,3.0
296,1.0,1,37.5,72.0,30.0,4.0,4.0,2.0
297,1.0,1,36.5,100.0,24.0,3.0,3.0,1.0
298,1.0,1,37.2,40.0,20.0,NaN,NaN,3.0

In [103]:
hd['rectal temperature'] = hd['rectal temperature'].astype(float)

In [105]:
#выбросы по температуре
q1 = hd['rectal temperature'].quantile(0.25)
q3 = hd['rectal temperature'].quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - (1.5 * iqr) 
upper_bound = q3 + (1.5 * iqr)
remove_outliers = hd[hd['rectal temperature'].between(lower_bound, upper_bound, inclusive=True)]
remove_outliers

,surgery?,age,rectal temperature,pulse,respiratory rate,temp of extremities,pain,outcome
0,1.0,1,39.2,88.0,20.0,NaN,3.0,3.0
1,2.0,1,38.3,40.0,24.0,1.0,3.0,1.0
2,1.0,9,39.1,164.0,84.0,4.0,2.0,2.0
3,2.0,1,37.3,104.0,35.0,NaN,NaN,2.0
5,1.0,1,37.9,48.0,16.0,1.0,3.0,1.0
...,...,...,...,...,...,...,...,...
291,1.0,1,37.0,66.0,20.0,1.0,4.0,2.0
293,2.0,1,38.5,40.0,16.0,1.0,2.0,1.0
295,2.0,1,37.2,72.0,24.0,3.0,4.0,3.0
296,1.0,1,37.5,72.0,30.0,4.0,4.0,2.0
298,1.0,1,37.2,40.0,20.0,NaN,NaN,3.0

In [118]:
#Пропуски в столбце боли можно заполнить по данным столбца исхода, предполагая, что есть зависимость его от степени боли
print(hd.groupby('outcome')['pain'].median())

outcome
1.0    3.0
2.0    4.0
3.0    3.0
Name: pain, dtype: float64

In [119]:
fill_median_by_outcome = hd
fill_median_by_outcome['pain'].fillna(hd.groupby('outcome')['pain'].transform('median'), inplace=True)

In [120]:
#Пропуски в столбцах температур и пульса можно заполнить, группируя по боли. Т.к. степень боли может определяться как раз этим
print(hd.groupby('pain')['rectal temperature'].median())

pain
1.0    38.20
2.0    38.30
3.0    38.15
4.0    38.00
5.0    38.00
Name: rectal temperature, dtype: float64

In [121]:
fill_median_by_pain = hd
fill_median_by_pain['rectal temperature'].fillna(hd.groupby('pain')['rectal temperature'].transform('median'), inplace=True)

In [122]:
print(hd.groupby('pain')['pulse'].median())

pain
1.0    48.0
2.0    78.0
3.0    60.0
4.0    80.0
5.0    89.0
Name: pulse, dtype: float64

In [123]:
fill_median_by_pain = hd
fill_median_by_pain['pulse'].fillna(hd.groupby('pain')['pulse'].transform('median'), inplace=True)

In [124]:
print(hd.groupby('pain')['temp of extremities'].median())

pain
1.0    1.5
2.0    3.0
3.0    2.0
4.0    3.0
5.0    3.0
Name: temp of extremities, dtype: float64

In [125]:
fill_median_by_pain = hd
fill_median_by_pain['temp of extremities'].fillna(hd.groupby('pain')['temp of extremities'].transform('median'), inplace=True)

In [127]:
print(hd.groupby('pain')['respiratory rate'].median())

pain
1.0    20.0
2.0    32.0
3.0    24.0
4.0    30.0
5.0    30.0
Name: respiratory rate, dtype: float64

In [128]:
fill_median_by_pain = hd
fill_median_by_pain['respiratory rate'].fillna(hd.groupby('pain')['respiratory rate'].transform('median'), inplace=True)

In [130]:
fill_median_by_pain.head()

,surgery?,age,rectal temperature,pulse,respiratory rate,temp of extremities,pain,outcome
0,1.0,1,39.2,88.0,20.0,2.0,3.0,3.0
1,2.0,1,38.3,40.0,24.0,1.0,3.0,1.0
2,1.0,9,39.1,164.0,84.0,4.0,2.0,2.0
3,2.0,1,37.3,104.0,35.0,3.0,4.0,2.0
4,2.0,1,38.3,78.0,32.0,2.0,2.0,1.0

In [133]:
hd.tail(10)

,surgery?,age,rectal temperature,pulse,respiratory rate,temp of extremities,pain,outcome
289,2.0,1,38.60,45.0,16.0,2.0,1.0,1.0
290,1.0,1,38.90,80.0,44.0,3.0,2.0,2.0
291,1.0,1,37.00,66.0,20.0,1.0,4.0,2.0
292,1.0,1,38.15,78.0,24.0,3.0,3.0,3.0
293,2.0,1,38.50,40.0,16.0,1.0,2.0,1.0
294,1.0,1,38.30,120.0,70.0,4.0,2.0,3.0
295,2.0,1,37.20,72.0,24.0,3.0,4.0,3.0
296,1.0,1,37.50,72.0,30.0,4.0,4.0,2.0
297,1.0,1,36.50,100.0,24.0,3.0,3.0,1.0
298,1.0,1,37.20,40.0,20.0,2.0,3.0,3.0