# Задание 1
Вернемся к набору данных о видеоиграх.

Ответьте на следующие вопросы:

1) Как критики относятся к спортивным играм?
2) Критикам нравятся больше игры на PC или на PS4?
3) Критикам больше нравятся стрелялки или стратегии?

Для каждого вопроса:

* сформулируйте нулевую и альтернативную гипотезы;
* выберите пороговый уровень статистической значимости;
* опишите полученные результаты статистического теста.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('vgsales.csv')
df

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16714,Samurai Warriors: Sanada Maru,PS3,2016.0,Action,Tecmo Koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16715,LMA Manager 2007,X360,2006.0,Sports,Codemasters,0.00,0.01,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16716,Haitaka no Psychedelica,PSV,2016.0,Adventure,Idea Factory,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16717,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16718,Winning Post 8 2016,PSV,2016.0,Simulation,Tecmo Koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16719 entries, 0 to 16718
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             16717 non-null  object
 1   Platform         16719 non-null  object
 2   Year_of_Release  16450 non-null  float64
 3   Genre            16717 non-null  object
 4   Publisher        16665 non-null  object
 5   NA_Sales         16719 non-null  float64
 6   EU_Sales         16719 non-null  float64
 7   JP_Sales         16719 non-null  float64
 8   Other_Sales      16719 non-null  float64
 9   Global_Sales     16719 non-null  float64
 10  Critic_Score     8137 non-null   float64
 11  Critic_Count     8137 non-null   float64
 12  User_Score       10015 non-null  object
 13  User_Count       7590 non-null   float64
 14  Developer        10096 non-null  object
 15  Rating           9950 non-null   object
dtypes: float64(9), object(7)
memory usage: 2.0+ MB

### 1) Как критики относятся к спортивным играм? 
Проверим, если критики ставят оценку играм больше 70, значит они хорошо относятся к ним, иначе недостаточно хорошо. 

H0: средняя удовлетворенность критиков спортивными играми <= 70
H1: средняя удовлетворенность критиков спортивными играми 70

alpha = 0.05

In [14]:
#офильтруем спортивные игры
sports = df.loc[(df['Genre'] == 'Sports')&(df['Critic_Score'] > 0)]
sports

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
13,Wii Fit,Wii,2007.0,Sports,Nintendo,8.92,8.03,3.60,2.15,22.70,80.0,63.0,7.7,146.0,Nintendo,E
15,Wii Fit Plus,Wii,2009.0,Sports,Nintendo,9.01,8.49,2.53,1.77,21.79,80.0,33.0,7.4,52.0,Nintendo,E
77,FIFA 16,PS4,2015.0,Sports,Electronic Arts,1.12,6.12,0.06,1.28,8.57,82.0,42.0,4.3,896.0,EA Sports,E
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16456,NHL 2K7,XB,2006.0,Sports,Take-Two Interactive,0.01,0.00,0.00,0.00,0.01,78.0,8.0,tbd,NaN,Kush Games,E10+
16478,John Daly's ProStroke Golf,X360,2010.0,Sports,O-Games,0.01,0.00,0.00,0.00,0.01,57.0,5.0,NaN,NaN,Gusto Games,E
16532,Pro Evolution Soccer 2010,PC,2009.0,Sports,Konami Digital Entertainment,0.00,0.01,0.00,0.00,0.01,78.0,8.0,6.9,49.0,Konami,E
16550,Wade Hixton's Counter Punch,GBA,2004.0,Sports,"Destination Software, Inc",0.01,0.00,0.00,0.00,0.01,78.0,13.0,9.5,4.0,Inferno Games,T
16555,Winning Eleven: Pro Evolution Soccer 2007,PC,2006.0,Sports,Konami Digital Entertainment,0.00,0.01,0.00,0.00,0.01,88.0,6.0,NaN,NaN,KCET,E

In [29]:
from scipy import stats as st

alpha = 0.05
result = st.ttest_1samp(sports['Critic_Score'], 70, alternative='greater')

print(sports['Critic_Score'].mean())
print(result)

if result.pvalue < alpha: 
    print('Отвергаем нулевую гипотезу, средняя оценка больше 70')
else:
    print('Не отвергаем нулевую нулевую гипотезу, средняя оценка меньше 70')

71.96817420435511
Ttest_1sampResult(statistic=4.900329475499578, pvalue=5.442744598708131e-07)
Отвергаем нулевую гипотезу, средняя оценка больше 70

p-value меньше 5% - мы получили значимый результат. p-value меньше уровня значимости, нулевую гипотезу отвергаем. это значит, что критики относятся к спортивным играм достаточно хорошо: оценка 70 и больше из 100

### 2) Критикам нравятся больше игры на PC или на PS4?

Выясняем, есть ли разница между средними значениями оценок игр на РС или PS4? Если разница значима, сравним средние значения и выясним, что нравится больше.

H0: средние оценки одинаковые
H1: средние оценки различаются

alpha = 0.05

In [30]:
#готовим выборки
PC = df.loc[(df['Platform'] == 'PC')&(df['Critic_Score'] > 0)]
PC

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
85,The Sims 3,PC,2009.0,Simulation,Electronic Arts,0.99,6.42,0.00,0.60,8.01,86.0,75.0,7.6,886.0,The Sims Studio,T
138,World of Warcraft,PC,2004.0,Role-Playing,Activision,0.08,6.21,0.00,0.00,6.29,93.0,57.0,7.3,2182.0,Blizzard Entertainment,T
192,Diablo III,PC,2012.0,Role-Playing,Activision,2.44,2.16,0.00,0.54,5.14,88.0,86.0,4,9629.0,Blizzard Entertainment,M
218,StarCraft II: Wings of Liberty,PC,2010.0,Strategy,Activision,2.57,1.68,0.00,0.58,4.84,93.0,82.0,8.2,3052.0,Blizzard Entertainment,T
284,Half-Life,PC,1997.0,Shooter,Vivendi Games,4.03,0.00,0.09,0.00,4.12,96.0,24.0,9.1,3161.0,Valve Software,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16644,Hospital Tycoon,PC,2007.0,Strategy,Codemasters,0.00,0.01,0.00,0.00,0.01,51.0,8.0,3.8,29.0,Big Red Software,E10+
16696,Metal Gear Solid V: Ground Zeroes,PC,2014.0,Action,Konami Digital Entertainment,0.00,0.01,0.00,0.00,0.01,80.0,20.0,7.6,412.0,Kojima Productions,M
16700,Breach,PC,2011.0,Shooter,Destineer,0.01,0.00,0.00,0.00,0.01,61.0,12.0,5.8,43.0,Atomic Games,T
16706,STORM: Frontline Nation,PC,2011.0,Strategy,Unknown,0.00,0.01,0.00,0.00,0.01,60.0,12.0,7.2,13.0,SimBin,E10+
16709,15 Days,PC,2009.0,Adventure,DTP Entertainment,0.00,0.01,0.00,0.00,0.01,63.0,6.0,5.8,8.0,DTP Entertainment,NaN

In [17]:
PS4 = df.loc[(df['Platform'] == 'PS4')&(df['Critic_Score'] > 0)]
PS4

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
42,Grand Theft Auto V,PS4,2014.0,Action,Take-Two Interactive,3.96,6.31,0.38,1.97,12.61,97.0,66.0,8.3,2899.0,Rockstar North,M
77,FIFA 16,PS4,2015.0,Sports,Electronic Arts,1.12,6.12,0.06,1.28,8.57,82.0,42.0,4.3,896.0,EA Sports,E
92,Call of Duty: Advanced Warfare,PS4,2014.0,Shooter,Activision,2.81,3.48,0.14,1.23,7.66,83.0,39.0,5.7,1443.0,Sledgehammer Games,M
94,FIFA 17,PS4,2016.0,Sports,Electronic Arts,0.66,5.75,0.08,1.11,7.59,85.0,41.0,5,398.0,"EA Sports, EA Vancouver",E
105,Fallout 4,PS4,2015.0,Role-Playing,Bethesda Softworks,2.53,3.27,0.24,1.13,7.16,87.0,58.0,6.5,4228.0,Bethesda Game Studios,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16490,Super Dungeon Bros,PS4,2016.0,Action,Nordic Games,0.01,0.00,0.00,0.00,0.01,42.0,9.0,2.3,7.0,React Games,E10+
16503,Sherlock Holmes: The Devil's Daughter,PS4,2016.0,Adventure,Bigben Interactive,0.01,0.00,0.00,0.00,0.01,70.0,27.0,6.8,64.0,Frogwares,T
16504,Root Letter,PS4,2016.0,Adventure,PQube,0.00,0.00,0.01,0.00,0.01,69.0,13.0,7.5,11.0,Kadokawa,NaN
16530,Dungeons 2,PS4,2016.0,Role-Playing,Kalypso Media,0.01,0.00,0.00,0.00,0.01,61.0,9.0,7.9,14.0,Kalypso,T
16534,Carmageddon: Max Damage,PS4,2016.0,Action,Stainless Games,0.01,0.00,0.00,0.00,0.01,51.0,28.0,5.5,39.0,Stainless Games,M

In [31]:
alpha = 0.05
result = st.ttest_ind(PC['Critic_Score'], PS4['Critic_Score'], equal_var=False)

print('PC', PC['Critic_Score'].mean())
print('PS4', PS4['Critic_Score'].mean())

print(result)

if (result.pvalue < alpha):
    print('Отвергаем нулевую гипотезу, критики по разному относятся к платформам')
else:
    print('Не отвергаем нулевую гипотезу, у критиков есть предпочтения между двумя платформами')

PC 75.92867132867133
PS4 72.09126984126983
Ttest_indResult(statistic=4.3087588262138725, pvalue=2.067249157283479e-05)
Отвергаем нулевую гипотезу, критики по разному относятся к платформам

p-value меньше 5% - мы получили значимый результат. p-value меньше уровня значимости, нулевую гипотезу отвергаем. это значит, что критики относятся к платформам не одинаково. сравним средние оценки и узнаем, что нравится больше

In [22]:
if (PC['Critic_Score'].mean() < PS4['Critic_Score'].mean()):
    print('Критикам больше нравятся игры на PS4')
else:
    print('Критикам больше нравятся игры на PC')

Критикам больше нравятся игры на PC

### 3) Критикам больше нравятся стрелялки или стратегии?

Выясняем, есть ли разница между средними значениями оценок стрелялок или стратегий? Если разница значима, сравним средние значения и выясним, что нравится больше.

H0: средние оценки одинаковые H1: средние оценки различаются

alpha = 0.05

In [40]:
#готовим выборки
shooter = df.loc[(df['Genre'] == 'Shooter')&(df['Critic_Score'] > 0)]
shooter

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
29,Call of Duty: Modern Warfare 3,X360,2011.0,Shooter,Activision,9.04,4.24,0.13,1.32,14.73,88.0,81.0,3.4,8713.0,"Infinity Ward, Sledgehammer Games",M
32,Call of Duty: Black Ops,X360,2010.0,Shooter,Activision,9.70,3.68,0.11,1.13,14.61,87.0,89.0,6.3,1454.0,Treyarch,M
34,Call of Duty: Black Ops II,PS3,2012.0,Shooter,Activision,4.99,5.73,0.65,2.42,13.79,83.0,21.0,5.3,922.0,Treyarch,M
35,Call of Duty: Black Ops II,X360,2012.0,Shooter,Activision,8.25,4.24,0.07,1.12,13.67,83.0,73.0,4.8,2256.0,Treyarch,M
36,Call of Duty: Modern Warfare 2,X360,2009.0,Shooter,Activision,8.52,3.59,0.08,1.28,13.47,94.0,100.0,6.3,2698.0,Infinity Ward,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16433,Greg Hastings' Tournament Paintball Max'd,PS2,2006.0,Shooter,Activision,0.01,0.00,0.00,0.00,0.01,70.0,8.0,9.2,32.0,Activision Value,E10+
16452,Inversion,PC,NaN,Shooter,Namco Bandai Games,0.01,0.00,0.00,0.00,0.01,59.0,6.0,6.7,107.0,Saber Interactive,M
16541,Clive Barker's Jericho,PC,2007.0,Shooter,Codemasters,0.00,0.01,0.00,0.00,0.01,63.0,25.0,7.5,218.0,"Mercury Steam, Alchemic Productions",M
16581,Space Raiders,GC,2003.0,Shooter,Taito,0.01,0.00,0.00,0.00,0.01,40.0,8.0,tbd,NaN,Taito Corporation,T
16700,Breach,PC,2011.0,Shooter,Destineer,0.01,0.00,0.00,0.00,0.01,61.0,12.0,5.8,43.0,Atomic Games,T

In [39]:
strategy = df.loc[(df['Genre'] == 'Strategy')&(df['Critic_Score'] > 0)]
strategy

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
218,StarCraft II: Wings of Liberty,PC,2010.0,Strategy,Activision,2.57,1.68,0.00,0.58,4.84,93.0,82.0,8.2,3052.0,Blizzard Entertainment,T
582,Halo Wars,X360,2009.0,Strategy,Microsoft Game Studios,1.54,0.80,0.04,0.24,2.62,82.0,92.0,7.2,454.0,Ensemble Studios,T
1078,Sid Meier's Civilization V,PC,2010.0,Strategy,Take-Two Interactive,0.98,0.52,0.00,0.17,1.68,90.0,70.0,7.9,2280.0,Firaxis Games,E10+
1095,StarCraft II: Heart of the Swarm,PC,2013.0,Strategy,Activision,0.83,0.66,0.00,0.18,1.67,86.0,68.0,7.9,1346.0,Blizzard Entertainment,T
1128,Pikmin,GC,2001.0,Strategy,Nintendo,0.78,0.25,0.56,0.04,1.63,89.0,39.0,8.7,121.0,Nintendo,E
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16423,Battlestations: Midway,PC,2007.0,Strategy,Eidos Interactive,0.00,0.01,0.00,0.00,0.01,76.0,20.0,7.3,46.0,Eidos Interactive,T
16457,Act of Aggression,PC,2015.0,Strategy,Focus Home Interactive,0.00,0.01,0.00,0.00,0.01,71.0,37.0,7.1,93.0,Eugen Systems,NaN
16573,The Eye of Judgment: Legends,PSP,2010.0,Strategy,Sony Computer Entertainment,0.00,0.00,0.01,0.00,0.01,69.0,17.0,7.9,16.0,SCEI,E10+
16644,Hospital Tycoon,PC,2007.0,Strategy,Codemasters,0.00,0.01,0.00,0.00,0.01,51.0,8.0,3.8,29.0,Big Red Software,E10+
16706,STORM: Frontline Nation,PC,2011.0,Strategy,Unknown,0.00,0.01,0.00,0.00,0.01,60.0,12.0,7.2,13.0,SimBin,E10+

In [41]:
alpha = 0.05
result = st.ttest_ind(shooter['Critic_Score'], strategy['Critic_Score'], equal_var=False)

print('Shooter', shooter['Critic_Score'].mean())
print('Strategy', strategy['Critic_Score'].mean())

print(result)

if (result.pvalue < alpha):
    print('Отвергаем нулевую гипотезу, критики по разному относятся к выбранным жанрам')
else:
    print('Не отвергаем нулевую гипотезу, у критиков есть предпочтения между двумя жанрами')

Shooter 70.18114406779661
Strategy 72.08609271523179
Ttest_indResult(statistic=-2.2972408230640315, pvalue=0.021938989522304823)
Отвергаем нулевую гипотезу, критики по разному относятся к выбранным жанрам

p-value меньше 5% - мы получили значимый результат. p-value меньше уровня значимости, нулевую гипотезу отвергаем. это значит, что критики относятся к жанрам не одинаково. сравним средние оценки и узнаем, что нравится больше

In [42]:
if (shooter['Critic_Score'].mean() < strategy['Critic_Score'].mean()):
    print('Критикам больше нравятся стратегии')
else:
    print('Критикам больше нравятся стрелялки')

Критикам больше нравятся стратегии

# Задание 2
Реализуйте базовую модель логистической регрессии для классификации текстовых сообщений (используемые данные здесь) по признаку спама. Для этого:

1) Привидите весь текст к нижнему регистру;
2) Удалите мусорные символы;
3) Удалите стоп-слова;
4) Привидите все слова к нормальной форме;
5) Преобразуйте все сообщения в вектора TF-IDF. Вам поможет следующий код:

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(df.Message)
names = tfidf.get_feature_names()
tfidf_matrix = pd.DataFrame(tfidf_matrix.toarray(), columns=names)

Можете поэкспериментировать с параметрами TfidfVectorizer;

6) Разделите данные на тестовые и тренировочные в соотношении 30/70, укажите random_state=42. Используйте train_test_split;
7) Постройте модель логистической регрессии, укажите random_state=42, оцените ее точность на тестовых данных;
8) Опишите результаты при помощи confusion_matrix;
9) Постройте датафрейм, который будет содержать все исходные тексты сообщений, классифицированные неправильно (с указанием фактического и предсказанного).

In [44]:
import glob
import re

In [45]:
spam = pd.read_csv('spam.csv')
spam

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [54]:
# 1. приведем все слова к нижнему регистру

 = spam['Message'].str.lower()
spam

     Category                                            Message
0         ham  go until jurong point, crazy.. available only ...
1         ham                      ok lar... joking wif u oni...
2        spam  free entry in 2 a wkly comp to win fa cup fina...
3         ham  u dun say so early hor... u c already then say...
4         ham  nah i don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  this is the 2nd time we have tried 2 contact u...
5568      ham               will ü b going to esplanade fr home?
5569      ham  pity, * was in mood for that. so...any other s...
5570      ham  the guy did some bitching but i acted like i'd...
5571      ham                         rofl. its true to its name

[5572 rows x 2 columns]

In [56]:
# 2. уберем все служебные символы

spam['Message'] = [re.sub('[\W_]+',' ', text) for text in spam['Message']]
spam

     Category                                            Message
0         ham  go until jurong point crazy available only in ...
1         ham                           ok lar joking wif u oni
2        spam  free entry in 2 a wkly comp to win fa cup fina...
3         ham       u dun say so early hor u c already then say
4         ham  nah i don t think he goes to usf he lives arou...
...       ...                                                ...
5567     spam  this is the 2nd time we have tried 2 contact u...
5568      ham               will ü b going to esplanade fr home
5569      ham  pity was in mood for that so any other suggest...
5570      ham  the guy did some bitching but i acted like i d...
5571      ham                          rofl its true to its name

[5572 rows x 2 columns]

In [58]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\khoroshkova\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [61]:
#3. удалим стоп-слова
from nltk.corpus import stopwords
stop = stopwords.words('english')

spam['Message'].apply(lambda x: [item for item in x if item not in stop])
spam

     Category                                            Message
0         ham  go until jurong point crazy available only in ...
1         ham                           ok lar joking wif u oni
2        spam  free entry in 2 a wkly comp to win fa cup fina...
3         ham       u dun say so early hor u c already then say
4         ham  nah i don t think he goes to usf he lives arou...
...       ...                                                ...
5567     spam  this is the 2nd time we have tried 2 contact u...
5568      ham               will ü b going to esplanade fr home
5569      ham  pity was in mood for that so any other suggest...
5570      ham  the guy did some bitching but i acted like i d...
5571      ham                          rofl its true to its name

[5572 rows x 2 columns]

In [63]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\khoroshkova\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\wordnet.zip.

True

In [86]:
#4. делаем лемматизацию

from nltk.stem import WordNetLemmatizer

w_tokenizer = nltk.tokenize.WhitespaceTokenizer()
lemmatizer = nltk.stem.WordNetLemmatizer()

def lemmatize_text(text): #функция лемматизации входного текста
    return [lemmatizer.lemmatize(w) for w in w_tokenizer.tokenize(text)]

spam['message_lemmatized'] = spam.Message.apply(lemmatize_text) #применяем функцию для датафрейма
spam

,Category,Message,message_lemmatized
0,ham,go until jurong point crazy available only in ...,"[go, until, jurong, point, crazy, available, o..."
1,ham,ok lar joking wif u oni,"[ok, lar, joking, wif, u, oni]"
2,spam,free entry in 2 a wkly comp to win fa cup fina...,"[free, entry, in, 2, a, wkly, comp, to, win, f..."
3,ham,u dun say so early hor u c already then say,"[u, dun, say, so, early, hor, u, c, already, t..."
4,ham,nah i don t think he goes to usf he lives arou...,"[nah, i, don, t, think, he, go, to, usf, he, l..."
...,...,...,...
5567,spam,this is the 2nd time we have tried 2 contact u...,"[this, is, the, 2nd, time, we, have, tried, 2,..."
5568,ham,will ü b going to esplanade fr home,"[will, ü, b, going, to, esplanade, fr, home]"
5569,ham,pity was in mood for that so any other suggest...,"[pity, wa, in, mood, for, that, so, any, other..."
5570,ham,the guy did some bitching but i acted like i d...,"[the, guy, did, some, bitching, but, i, acted,..."
5571,ham,rofl its true to its name,"[rofl, it, true, to, it, name]"

In [87]:
import string

def list_to_str(text): #функция возвращения строки из списка
        return ' '.join(text)

spam['message_lemmatized'] = [list_to_str(l) for l in spam['message_lemmatized']]
spam

,Category,Message,message_lemmatized
0,ham,go until jurong point crazy available only in ...,go until jurong point crazy available only in ...
1,ham,ok lar joking wif u oni,ok lar joking wif u oni
2,spam,free entry in 2 a wkly comp to win fa cup fina...,free entry in 2 a wkly comp to win fa cup fina...
3,ham,u dun say so early hor u c already then say,u dun say so early hor u c already then say
4,ham,nah i don t think he goes to usf he lives arou...,nah i don t think he go to usf he life around ...
...,...,...,...
5567,spam,this is the 2nd time we have tried 2 contact u...,this is the 2nd time we have tried 2 contact u...
5568,ham,will ü b going to esplanade fr home,will ü b going to esplanade fr home
5569,ham,pity was in mood for that so any other suggest...,pity wa in mood for that so any other suggestion
5570,ham,the guy did some bitching but i acted like i d...,the guy did some bitching but i acted like i d...
5571,ham,rofl its true to its name,rofl it true to it name

In [97]:
#5. преобразование в вектора

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(spam['message_lemmatized'])
names = tfidf.get_feature_names()
tfidf_matrix = pd.DataFrame(tfidf_matrix.toarray(), columns=names)
tfidf_matrix

,00,000,000pes,008704050406,0089,0121,01223585236,01223585334,0125698789,02,...,zhong,zindgi,zoe,zogtorius,zoom,zouk,zyada,èn,ú1,〨ud
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5567,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5568,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5569,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5570,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5571,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [98]:
#6-7. делим данные на тестовые и тренировочные и строим модель

from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.model_selection import train_test_split

X = spam['message_lemmatized']
y = spam['Category']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
logreg = LogisticRegression()
logreg.fit(X_train, y_train)

ValueError: could not convert string to float: 'quite late lar ard 12 anyway i wun b drivin'

In [ ]:
#оцениваем точность

y_pred = logreg.predict(X_test)
print('Точность на тестовой выборке:'.format(logreg.score(X_test, y_test)))

In [ ]:
#8. матрица confusion_matrix

from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)
confusion_matrix

In [ ]:
#9. строим датафрейм

spam['Category_pred'] = spam.Category.apply(y_pred)
spam_filtered = spam.loc[(spam['Category'] != spam['Category_pred'])]
spam_filtered